name: Service-account-creation

on:
    repository_dispatch:
        types: [service-account-requested]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6.2.0
              with:
                  python-version: "3.14.2"

            - name: Install Poetry
              run: |
                  curl -sSL https://install.python-poetry.org | python3 -
                  echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

            - name: Install dependencies with Poetry
              run: |
                  poetry install --no-root
                
            - name: Set PYTHONPATH to include the source directory
              run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

            - name: Run scrip
              run : |
                    cd scripts
                    echo '${{ toJson(github.event.client_payload) }}' | poetry run python main.py
                    
